# Generated by Django 5.2.15 on 2026-06-27 07:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=16)),
                ('actor_id', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=64)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
                ('password_hash', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name_plural': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('department', models.CharField(choices=[('BCOM', 'BCOM'), ('BSC', 'BSC')], max_length=8)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('events_count', models.PositiveIntegerField(default=0)),
                ('events_required', models.PositiveIntegerField(default=5)),
                ('password_hash', models.CharField(blank=True, max_length=256)),
                ('semester_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Hackathon', 'Hackathon'), ('Fest', 'Fest'), ('Workshop', 'Workshop'), ('Other', 'Other')], max_length=32)),
                ('event_level', models.CharField(choices=[('Local', 'Local'), ('State', 'State'), ('National', 'National')], max_length=16)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('venue_start', models.DateTimeField()),
                ('venue_end', models.DateTimeField()),
                ('base_xp', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ExemptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('file_name', models.CharField(max_length=256)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('frozen_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemptions', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Participant', 'Participant'), ('Volunteer', 'Volunteer'), ('Winner', 'Winner')], max_length=16)),
                ('xp_awarded', models.PositiveIntegerField()),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'event')},
            },
        ),
    ]
