# Generated by Django 5.2.15 on 2026-06-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Environmental Studies (EVS)', max_length=100)),
                ('semester', models.CharField(help_text='e.g., Sem 4', max_length=20)),
                ('min_events_required', models.IntegerField(default=5)),
                ('max_academic_marks', models.IntegerField(default=100, help_text='The ultimate marks boundary for the university sheet')),
            ],
        ),
        migrations.CreateModel(
            name='ActionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_performed', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('scope_points', models.IntegerField(choices=[(20, 'Intra-College (20 XP)'), (50, 'Inter-College (50 XP)'), (100, 'National Level (100 XP)')])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('associated_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.subjectcontainer')),
            ],
        ),
    ]
